// Popup content definitions for all calculated fields
// Each popup includes: definition, formula (if applicable), and impact explanation

export interface PopupContent {
  title: string;
  definition: string;
  formula?: string;
  impact: string;
}

export const POPUP_CONTENT: Record<string, PopupContent> = {
  // ============================================
  // TAX RATES SECTION
  // ============================================

  'federal-st-rate': {
    title: 'Federal Ordinary/ST Rate',
    definition:
      'Your marginal federal tax rate on ordinary income and short-term capital gains (assets held less than 1 year).',
    formula: 'Tax Bracket Rate (10-37%) + NIIT (3.8% if AGI > $250K MFJ or $200K Single)',
    impact:
      'Higher ordinary rates increase the value of ST→LT conversion and ordinary loss deductions.',
  },

  'federal-lt-rate': {
    title: 'Federal LT Capital Gains Rate',
    definition:
      'Your marginal federal tax rate on long-term capital gains (assets held more than 1 year).',
    formula: '0%/15%/20% based on income + NIIT (3.8% if applicable)',
    impact: 'Lower than ordinary rates - this differential creates the tax arbitrage opportunity.',
  },

  'state-rate': {
    title: 'State Tax Rate',
    definition: 'Your state income tax rate. Most states tax capital gains as ordinary income.',
    formula: 'Varies by state (0% in TX, FL, WA; up to 13.3% in CA)',
    impact:
      'Higher state rates increase overall tax burden but also increase savings from the strategy.',
  },

  'combined-st-rate': {
    title: 'Combined Ordinary Rate',
    definition: 'Total tax rate on ordinary income and short-term capital gains.',
    formula: 'Federal Ordinary Rate + State Rate',
    impact: 'This is the rate saved when ordinary losses offset W-2 income.',
  },

  'combined-lt-rate': {
    title: 'Combined LT Rate',
    definition: 'Total tax rate on long-term capital gains.',
    formula: 'Federal LT Rate + State Rate',
    impact: 'This is the effective rate paid on strategy LT gains.',
  },

  'st-lt-benefit': {
    title: 'ST→LT Conversion Benefit',
    definition: 'Tax savings per dollar when converting short-term gains to long-term treatment.',
    formula: 'Combined Ordinary Rate - Combined LT Rate',
    impact:
      'This differential drives the core value of matching QFAF ST gains with collateral ST losses.',
  },

  // ============================================
  // STRATEGY SIZING SECTION
  // ============================================

  'collateral-value': {
    title: 'Collateral Value',
    definition:
      'The amount invested in the direct indexing (Core) or pledged as collateral (Overlay) strategy.',
    impact:
      'Larger collateral generates more ST losses, enabling larger QFAF allocation and greater tax benefits.',
  },

  'auto-sized-qfaf': {
    title: 'Auto-Sized QFAF',
    definition:
      'Qualified Family Agricultural Fund allocation, automatically sized to match collateral ST loss capacity.',
    formula: '(Collateral × Strategy ST Loss Rate) ÷ 150%',
    impact:
      'QFAF generates 150% ST gains and 150% ordinary losses annually. Proper sizing ensures ST gains are fully offset.',
  },

  'total-exposure': {
    title: 'Total Exposure',
    definition: 'Combined value of collateral and QFAF investments.',
    formula: 'Collateral Value + QFAF Value',
    impact:
      'Total capital deployed in the strategy. Tax alpha is measured relative to this amount.',
  },

  'qfaf-ratio': {
    title: 'QFAF Ratio',
    definition: 'QFAF allocation as a percentage of collateral.',
    formula: 'QFAF Value ÷ Collateral Value × 100%',
    impact: 'Lower leverage strategies have lower ratios. Core 145/45 typically has ~8.7% ratio.',
  },

  'section-461-limit': {
    title: 'Section 461(l) Limit',
    definition:
      'Annual cap on excess business losses that can offset non-business income (W-2, interest, etc.).',
    formula:
      '$512,000 (MFJ) or $256,000 (Single/MFS/HOH) for 2026. Also limited by taxable income.',
    impact: 'Ordinary losses above this limit (or taxable income) become NOL carryforward.',
  },

  'year1-st-losses': {
    title: 'Year 1 ST Losses',
    definition: 'Short-term capital losses generated by the collateral strategy in year 1.',
    formula: 'Collateral Value × Strategy ST Loss Rate',
    impact: 'These losses offset QFAF ST gains, converting them to long-term treatment.',
  },

  'year1-st-gains': {
    title: 'Year 1 ST Gains',
    definition: 'Short-term capital gains generated by QFAF in year 1.',
    formula: 'QFAF Value × 150%',
    impact: 'Auto-sizing ensures these match collateral ST losses exactly.',
  },

  'net-st-position': {
    title: 'Net ST Position',
    definition: 'Result of matching QFAF ST gains against collateral ST losses.',
    formula: 'QFAF ST Gains - Collateral ST Losses',
    impact: 'Should be $0 or near-zero with proper auto-sizing.',
  },

  'year1-ordinary-losses': {
    title: 'Year 1 Ordinary Losses',
    definition: 'Ordinary losses generated by QFAF through its swap structure.',
    formula: 'QFAF Value × 150%',
    impact: 'These can offset W-2 income, subject to §461(l) limitation.',
  },

  'usable-ordinary-loss': {
    title: 'Usable Ordinary Loss',
    definition: 'Portion of QFAF ordinary losses that can offset income this year.',
    formula: 'min(QFAF Ordinary Losses, §461(l) Limit)',
    impact: 'Directly reduces taxable income at your marginal ordinary rate.',
  },

  'excess-to-nol': {
    title: 'Excess → NOL Carryforward',
    definition: 'Ordinary losses exceeding the §461(l) limit that become Net Operating Loss.',
    formula: 'QFAF Ordinary Losses - Usable Ordinary Loss',
    impact:
      'NOL can offset up to 80% of taxable income in future years, carried forward indefinitely.',
  },

  // ============================================
  // TAX BENEFIT BREAKDOWN
  // ============================================

  'ordinary-loss-benefit': {
    title: 'Ordinary Loss Tax Benefit',
    definition: 'Tax savings from QFAF ordinary losses offsetting W-2/ordinary income.',
    formula: 'Usable Ordinary Loss × Combined Ordinary Rate',
    impact: 'The primary driver of tax alpha. Higher ordinary rates = greater benefit.',
  },

  'st-lt-conversion-benefit': {
    title: 'Rate Arbitrage Benefit',
    definition:
      'Tax savings because gains are taxed at the lower long-term rate instead of the higher short-term/ordinary rate. QFAF short-term gains are offset by collateral short-term losses, converting them to long-term treatment.',
    formula: 'Matched ST Amount × (Ordinary Rate - LT Rate)',
    impact:
      'By matching QFAF ST gains with collateral ST losses, gains are effectively taxed at LT rates.',
  },

  'lt-gain-cost': {
    title: 'LT Gain Tax Cost',
    definition:
      'Tax paid on long-term capital gains realized from collateral strategy rebalancing.',
    formula: 'LT Gains Realized × Combined LT Rate',
    impact: 'A necessary cost of the strategy, but taxed at favorable long-term rates.',
  },

  'year1-tax-savings': {
    title: 'Net Year 1 Tax Savings',
    definition: 'Total tax benefit in Year 1 after accounting for all tax events.',
    formula: 'Ordinary Loss Benefit + ST→LT Benefit - LT Gain Cost',
    impact: 'Represents immediate tax alpha generated by the strategy.',
  },

  'nol-offset-benefit': {
    title: 'NOL Offset Benefit',
    definition:
      'Tax savings from using accumulated Net Operating Loss (NOL) carryforward to offset current year taxable income.',
    formula: 'NOL Used This Year × Combined Ordinary Rate',
    impact:
      "Starting in Year 2, accumulated NOL from prior years can offset up to 80% of taxable income, providing additional tax savings beyond the current year's ordinary loss deduction.",
  },

  'year2-tax-savings': {
    title: 'Net Year 2 Tax Savings',
    definition:
      'Total tax benefit in Year 2 after accounting for all tax events including NOL usage.',
    formula: 'Ordinary Loss Benefit + ST→LT Benefit + NOL Offset Benefit - LT Gain Cost',
    impact:
      'Year 2+ benefits include NOL carryforward usage, which can significantly increase tax savings compared to Year 1.',
  },

  // ============================================
  // RESULTS SUMMARY SECTION
  // ============================================

  'total-tax-savings': {
    title: 'Total Tax Savings',
    definition: 'Cumulative tax benefit over the 10-year projection period.',
    formula: 'Sum of (Baseline Tax - Actual Tax) for each year',
    impact: 'Represents the total value extracted from the strategy versus passive investing.',
  },

  'final-portfolio-value': {
    title: 'Final Portfolio Value',
    definition: 'Projected total value of collateral + QFAF at the end of year 10.',
    formula: 'Initial Investment × (1 + annual return)^10',
    impact: 'Shows the growth of your invested capital over the projection period.',
  },

  'effective-tax-alpha': {
    title: 'Annualized Tax Alpha',
    definition: 'Average annual tax savings as a percentage of total exposure.',
    formula: 'Total Tax Savings ÷ Total Exposure ÷ 10 years',
    impact:
      'Measures strategy efficiency - higher alpha means more tax benefit per dollar invested.',
  },

  'total-nol-generated': {
    title: 'Total NOL Generated',
    definition: 'Cumulative Net Operating Loss created over the projection period.',
    formula: 'Sum of Excess Ordinary Losses across all years',
    impact: 'This NOL can offset future income at 80% of taxable income per year.',
  },

  // ============================================
  // RESULTS TABLE COLUMNS
  // ============================================

  'col-year': {
    title: 'Year',
    definition: 'Projection year (1-10).',
    impact: 'Tax events are calculated based on portfolio values at the start of each year.',
  },

  'col-total-value': {
    title: 'Total Portfolio Value',
    definition: 'Combined value of QFAF and collateral investments.',
    formula: 'QFAF Value + Collateral Value (after annual return growth)',
    impact: 'Growing portfolio base increases absolute tax benefits in later years.',
  },

  'col-portfolio-value': {
    title: 'Total Portfolio Value',
    definition:
      'Combined value of collateral and QFAF positions. Click to expand and see individual components.',
    formula: 'Collateral Value + QFAF Value',
    impact:
      'The total market value of all strategy assets. Growth comes from market returns on both positions.',
  },

  'col-qfaf-value': {
    title: 'QFAF Value',
    definition: 'Market value of QFAF investment.',
    formula: 'Prior Year QFAF × (1 + annual return)',
    impact: 'Higher QFAF value generates larger ST gains and ordinary losses.',
  },

  'col-collateral-value': {
    title: 'Collateral Value',
    definition: 'Market value of direct indexing or pledged stock.',
    formula: 'Prior Year Collateral × (1 + annual return)',
    impact: 'Higher collateral generates more ST losses for offset capacity.',
  },

  'col-st-gains': {
    title: 'ST Gains (QFAF)',
    definition: 'Short-term capital gains generated by QFAF.',
    formula: 'QFAF Value × 150%',
    impact: 'Offset by collateral ST losses to achieve favorable LT treatment.',
  },

  'col-st-losses': {
    title: 'ST Losses (Collateral)',
    definition: 'Short-term capital losses from tax-loss harvesting and short closures.',
    formula: 'Collateral Value × Strategy ST Loss Rate',
    impact: 'Used to offset QFAF ST gains, converting them to LT treatment.',
  },

  'col-ordinary-loss': {
    title: 'Ordinary Loss',
    definition: 'Ordinary losses generated by QFAF swap structure.',
    formula: 'QFAF Value × 150%',
    impact: 'Can offset W-2/ordinary income, subject to §461(l) cap.',
  },

  'col-usable-loss': {
    title: 'Usable Ordinary Loss',
    definition: 'Ordinary loss amount deductible this year after §461(l) cap. Click to expand and see the gross loss generated, the usable amount, and any excess flowing to NOL carryforward.',
    formula: 'min(Gross Ordinary Loss, §461(l) Limit, Taxable Income)',
    impact: 'Reduces taxable income at marginal ordinary rate. Excess above the cap becomes NOL for future years.',
  },

  'col-excess-nol': {
    title: 'Excess → NOL',
    definition: 'Ordinary losses above §461(l) limit becoming NOL.',
    formula: 'Ordinary Loss - Usable Ordinary Loss',
    impact: 'Carried forward to offset future taxable income.',
  },

  'col-lt-gains': {
    title: 'LT Gains (Collateral)',
    definition: 'Long-term capital gains from collateral strategy rebalancing.',
    formula: 'Collateral Value × Strategy LT Gain Rate',
    impact: 'Taxed at favorable LT rates, a cost of the strategy.',
  },

  'col-cap-loss-income': {
    title: 'Capital Loss vs Income',
    definition:
      'Unused capital loss carryforward applied against ordinary income per IRC §1211(b).',
    formula: 'min(Remaining Capital Loss Carryforward, $3,000)',
    impact: 'Reduces ordinary income by up to $3,000/year, saving taxes at your marginal rate.',
  },

  'col-nol-used': {
    title: 'NOL Applied',
    definition:
      'Amount of prior-year NOL carryforward applied against this year\'s taxable income. Year 1 is always $0 because NOL generated in the current year cannot be used until the following year.',
    formula: 'min(Start-of-Year NOL Balance, 80% × Pre-NOL Taxable Income)',
    impact:
      'Reduces taxable income, but limited to 80% of pre-NOL taxable income per TCJA rules. When ordinary losses already reduce income near zero, little NOL can be applied.',
  },

  'col-tax-savings': {
    title: 'Tax Savings',
    definition: 'Net tax benefit for this year. Click to expand and see the gross benefits and costs that make up this number.',
    formula: 'Ord. Ded. + NOL Ben. + Rate Arb. + Cap Loss Benefit − LT Cost − ST Gain Cost',
    impact: 'Annual value extracted from the tax optimization strategy.',
  },

  'col-ord-loss-benefit': {
    title: 'Ordinary Deduction Benefit',
    definition: 'Tax savings from deducting the usable ordinary loss against W-2/ordinary income.',
    formula: 'Usable Ordinary Loss × Combined Ordinary Rate',
    impact: 'Usually the largest single benefit component. Capped by §461(l) limit.',
  },

  'col-nol-benefit': {
    title: 'NOL Usage Benefit',
    definition: 'Tax savings from applying prior-year NOL carryforward against this year\'s taxable income.',
    formula: 'NOL Applied × Combined Ordinary Rate',
    impact: 'Converts banked NOL into actual tax reduction. Limited to 80% of pre-NOL taxable income.',
  },

  'col-conversion-benefit': {
    title: 'Rate Arbitrage Benefit',
    definition: 'Tax savings because gains were taxed at the lower long-term capital gains rate instead of the higher short-term/ordinary rate. QFAF generates short-term gains that are offset by collateral short-term losses, converting them to long-term treatment.',
    formula: 'min(ST Gains, ST Losses) × (Ordinary Rate − LT Rate)',
    impact: 'Captures the rate differential between ordinary and LT rates.',
  },

  'col-lt-gain-cost': {
    title: 'LT Gain Cost',
    definition: 'Tax liability from long-term capital gains realized by the collateral portfolio.',
    formula: 'LT Gains Realized × Combined LT Rate',
    impact: 'The primary cost of the strategy. Offset by the benefits above.',
  },

  'col-cumulative-savings': {
    title: 'Cumulative Tax Savings',
    definition: 'Running total of tax savings through this year.',
    formula: 'Sum of Tax Savings from Year 1 to current year',
    impact: 'Shows total value accumulated from the strategy.',
  },

  'col-eff-rate': {
    title: 'Effective ST Loss Rate',
    definition:
      'The actual ST loss rate used for this year (includes decay and any custom overrides).',
    formula: 'Custom Rate OR (Base Rate × 0.93^(year-1))',
    impact: 'Edit rates using the "Edit Rates by Year" button. Changes affect ST losses harvested.',
  },

  'col-st-carryforward': {
    title: 'ST Capital Loss Carryforward',
    definition: 'Accumulated short-term capital losses not yet used.',
    formula: 'Prior C/F + Current Year Net ST Loss - Used vs LT Gains - $3K Ordinary',
    impact: 'Offsets future capital gains; $3K/year against ordinary income.',
  },

  'col-nol-carryforward': {
    title: 'NOL Carryforward',
    definition: 'Total unused NOL available for future years.',
    formula: 'Prior NOL + This Year Excess - NOL Used This Year',
    impact: 'Can offset 80% of future taxable income each year.',
  },

  'col-net-capital': {
    title: 'Net Capital Activity',
    definition:
      'The net result of all capital gains and losses for the year. Click to expand and see component details (ST Losses, LT Gains, ST Gains).',
    formula: 'QFAF ST Gains - Collateral ST Losses + Collateral LT Gains',
    impact:
      'With proper auto-sizing, net capital ≈ LT gains only (ST gains and losses offset). This is what flows to your tax return.',
  },

  'col-max-offset': {
    title: 'Max Shelter',
    definition:
      'Maximum income that could be sheltered from tax this year. Useful for planning when to exercise stock options or realize other taxable income. Click to expand for NOL details. In wind-down years (marked with *), this reflects available carryforward capacity only — no new losses are generated.',
    formula: '§461(l) Limit + Start-of-Year NOL Balance + Capital Loss Limit ($3K/$1.5K)',
    impact:
      'Higher values indicate better years to realize additional taxable income. The §461(l) limit renews annually; the NOL balance accumulates over time.',
  },

  'col-nol-activity': {
    title: 'NOL Change',
    definition:
      'Net change in NOL for the year. Shows whether NOL is building (+) or being used (−).',
    formula: 'NOL Generated (Excess Ordinary Loss) − NOL Used This Year',
    impact:
      'Positive values mean NOL is accumulating faster than it can be used. NOL usage is limited to 80% of taxable income per year.',
  },

  // ============================================
  // ADVANCED MODE - YEAR BY YEAR
  // ============================================

  'w2-income-override': {
    title: 'W-2 Income Override',
    definition: 'Override the annual income for this specific year.',
    impact: 'Affects §461(l) limit calculation and NOL usage (80% of taxable income).',
  },

  'cash-infusion': {
    title: 'Cash Infusion',
    definition: 'Additional capital added to the strategy in this year.',
    formula: 'Added to collateral at year start, triggers QFAF re-sizing',
    impact: 'Increases collateral base, which increases ST loss capacity and required QFAF.',
  },

  // ============================================
  // ADVANCED MODE - SENSITIVITY
  // ============================================

  'sens-federal-rate': {
    title: 'Federal Rate Change',
    definition: 'Model potential changes to federal tax rates.',
    formula: 'Adjusts both ordinary and LT federal rates by this amount',
    impact: 'Higher rates increase strategy value; lower rates decrease it.',
  },

  'sens-state-rate': {
    title: 'State Rate Change',
    definition: 'Model potential changes to state tax rates.',
    impact: 'Similar to federal - higher state rates increase strategy value.',
  },

  'sens-annual-return': {
    title: 'Annual Return',
    definition: 'Model different portfolio growth scenarios.',
    formula: 'Replaces default 0% growth rate for projections',
    impact: 'Negative returns show how strategy performs in bear markets.',
  },

  'sens-tracking-error': {
    title: 'Tracking Error Impact',
    definition: 'Model deviation from expected strategy performance.',
    formula: 'Multiplier on ST loss and LT gain rate variance',
    impact: 'Higher tracking error means more uncertainty in realized tax events.',
  },

  'sens-st-loss-variance': {
    title: 'ST Loss Rate Variance',
    definition: 'Model variation in tax-loss harvesting effectiveness.',
    formula: 'Adjusts strategy ST loss rate by this percentage',
    impact: 'Lower ST losses reduce offset capacity and strategy benefits.',
  },

  'sens-lt-gain-variance': {
    title: 'LT Gain Rate Variance',
    definition: 'Model variation in realized LT gains.',
    formula: 'Adjusts strategy LT gain rate by this percentage',
    impact: 'Higher LT gains increase tax cost; lower gains reduce cost.',
  },

  // ============================================
  // ADVANCED MODE - STRATEGY COMPARISON
  // ============================================

  'comp-qfaf-required': {
    title: 'QFAF Required',
    definition: 'QFAF allocation needed for this strategy.',
    formula: '(Collateral × ST Loss Rate) ÷ 150%',
    impact: 'Higher leverage strategies require proportionally more QFAF.',
  },

  'comp-tracking-error': {
    title: 'Tracking Error',
    definition: 'Expected deviation from benchmark returns.',
    impact: 'Higher tracking error means more return volatility vs. index.',
  },

  // ============================================
  // ADVANCED MODE - SETTINGS
  // ============================================

  'setting-qfaf-multiplier': {
    title: 'QFAF Multiplier',
    definition:
      'The rate at which QFAF generates both ST gains and ordinary losses relative to its market value.',
    formula: 'Default: 150% (1.50x)',
    impact: 'Changing this affects auto-sizing and all tax event calculations.',
  },

  'setting-qfaf-growth': {
    title: 'QFAF Growth',
    definition: 'Controls whether the QFAF position appreciates with market returns over time.',
    formula: 'Enabled: QFAF grows at (Annual Return - Financing Cost). Disabled: QFAF stays flat.',
    impact:
      'Disabling models scenarios where QFAF returns are eaten by fees, hedging costs, or manager underperformance. This reduces final portfolio value but does not affect annual tax benefits.',
  },

  'setting-wash-sale': {
    title: 'Wash Sale Disallowance',
    definition:
      'Percentage of ST losses disallowed due to wash sale rule violations when repurchasing substantially identical securities within 30 days.',
    formula: 'Effective ST Losses = Gross ST Losses × (1 - Wash Sale Rate)',
    impact:
      'Typically 5-15% of losses are disallowed. Higher rates reduce ST offset capacity and overall tax benefits.',
  },

  'setting-nol-offset': {
    title: 'NOL Offset Limit',
    definition:
      'Maximum percentage of taxable income that can be offset by NOL carryforward in any given year.',
    formula: 'Default: 80% (per TCJA post-2017 rules)',
    impact: 'Lower limits extend NOL usage over more years; higher limits accelerate utilization.',
  },

  'setting-annual-return': {
    title: 'Default Annual Return',
    definition: 'Assumed portfolio growth rate for multi-year projections.',
    formula: 'Default: 0% (no growth assumption)',
    impact: 'Higher returns compound portfolio value; lower returns reduce projected wealth.',
  },

  'setting-niit': {
    title: 'NIIT Rate',
    definition:
      'Net Investment Income Tax on investment income above thresholds ($250K MFJ, $200K Single).',
    formula: 'Default: 3.8%',
    impact: 'Added to capital gains rates for high earners.',
  },

  'setting-ltcg': {
    title: 'LTCG Rate',
    definition: 'Federal long-term capital gains rate (top bracket).',
    formula: 'Default: 20%',
    impact: 'Lower LT rates increase the value of ST→LT conversion.',
  },

  'setting-stcg': {
    title: 'Top Ordinary Rate',
    definition: 'Highest marginal federal ordinary income tax rate.',
    formula: 'Default: 37%',
    impact: 'Higher ordinary rates increase the value of ordinary loss deductions.',
  },

  // ============================================
  // EDI TAB — SUMMARY CARDS
  // ============================================

  'edi-potential-tax-protection': {
    title: 'Potential Tax Protection',
    definition:
      'The dollar value of accumulated carryforward if used to shelter a capital gain. This is contingent — it only materializes when a qualifying gain event occurs (stock sale, business exit, etc.).',
    formula: 'Final Carryforward × Combined LT Capital Gains Rate',
    impact:
      'This is the headline number, but remember it requires a gain event. Without one, CF sits unused. The "Realized Benefit" card shows certain value.',
  },

  'edi-realized-benefit': {
    title: 'Realized Benefit',
    definition:
      'Cumulative tax savings from the $3,000/year capital loss deduction against ordinary income (§1211(b)). This benefit is certain — it occurs every year regardless of whether a gain event happens.',
    formula: 'Sum of ($3K × (Combined ST Rate - NIIT Rate)) for each year',
    impact:
      'Small but certain. Over 10 years at ~50% combined rate, this is roughly $15K in guaranteed savings. It compounds when considered alongside the contingent CF protection.',
  },

  'edi-break-even-gain': {
    title: 'Break-Even Gain Event',
    definition:
      'The minimum capital gain that must be realized for the strategy to "pay for itself" — i.e., for CF tax savings to exceed cumulative financing costs net of realized benefits already banked.',
    formula: 'max(0, Cumulative Financing Cost - Cumulative Realized Benefit) ÷ Combined LT Rate',
    impact:
      'If a client expects a gain event larger than this amount, the strategy has positive expected value. Smaller gain events mean only partial cost recovery.',
  },

  'edi-tax-free-exit-year': {
    title: 'Tax-Free Exit Year',
    definition:
      'The earliest year at which accumulated carryforward exceeds the estimated embedded gain in the portfolio. After this point, the strategy can be fully unwound with zero exit tax.',
    formula: 'First year where Total CF ≥ Embedded Gain Estimate',
    impact:
      'A key milestone. Before this year, unwinding triggers some tax. After it, the client has optionality — they can exit tax-free or keep building CF for external events.',
  },

  'edi-protection-ratio': {
    title: 'Protection Ratio',
    definition:
      'How much tax protection (CF × LT rate) has been built per dollar of incremental financing cost. A ratio above 1.0× means the strategy has generated more protection value than it cost.',
    formula: '(Cumulative CF × Combined LT Rate) ÷ Cumulative Financing Cost',
    impact:
      'Higher is better. Ratios of 2-4× are typical for overlay strategies. This only has value if a gain event occurs — without one, the ratio is theoretical.',
  },

  // ============================================
  // EDI TAB — ASSUMPTIONS / INPUTS
  // ============================================

  'edi-collateral-value': {
    title: 'Collateral Value',
    definition:
      'The amount of securities pledged as collateral for the overlay strategy. The overlay creates long and short positions against this collateral without requiring additional cash.',
    impact:
      'Larger collateral generates more ST losses and builds CF faster, but also incurs proportionally more financing cost. $5-50M is the typical range for this strategy.',
  },

  'edi-annual-return': {
    title: 'Annual Portfolio Return',
    definition:
      'The assumed compound annual growth rate of the underlying portfolio. Applied to both gross portfolio value and the passive benchmark.',
    formula: 'Portfolio grows at (Annual Return - Financing Cost) per year for EDI; Annual Return for passive',
    impact:
      'Higher returns increase both the portfolio value and the embedded gain. The EDI strategy grows slower than passive due to financing drag.',
  },

  'edi-wash-sale-rate': {
    title: 'Wash Sale Rate',
    definition:
      'Percentage of harvested ST losses disallowed under IRC §1091 when the strategy repurchases substantially identical securities within 30 days. Default is 0% (ideal scenario).',
    formula: 'Effective ST Losses = Gross ST Losses × (1 - Wash Sale Rate)',
    impact:
      'Typical wash sale disallowance is 5-15%. Higher rates reduce CF accumulation and increase embedded gain. 0% represents the ideal — an upper bound on strategy performance.',
  },

  'edi-advisory-fee': {
    title: 'Advisory Fee Rate',
    definition:
      'The wealth management/RIA advisory fee charged on NAV (not gross exposure). This fee is common to all strategies (passive, trad DI, EDI) and is therefore excluded from incremental cost comparisons.',
    formula: 'Annual Fee = NAV × Advisory Fee Rate',
    impact:
      'Since this fee is paid regardless of strategy choice, it does not affect the relative comparison. It is tracked separately in the Strategy Cost section.',
  },

  'edi-broker-margin-rate': {
    title: 'Broker Margin Rate',
    definition:
      'The interest rate charged on margin borrowing. For overlay strategies, this applies only to the long leverage amount (margin debit), NOT the full account value.',
    formula: 'Margin Cost = Collateral × Long Leverage Ratio × Broker Margin Rate',
    impact:
      'The largest component of incremental financing cost. A 1% reduction in margin rate can save $45K/year on $10M collateral with 45% leverage.',
  },

  'edi-short-borrow-rate': {
    title: 'Short Borrow Rate',
    definition:
      'The fee paid to borrow shares for short positions. Also called the "hard-to-borrow" or "stock loan" fee. Applied to the short position notional.',
    formula: 'Borrow Cost = Collateral × Short Ratio × Short Borrow Rate',
    impact:
      'Usually 0.25-1.0% for liquid, easy-to-borrow names. Can spike for hard-to-borrow stocks. Lower rates directly reduce financing drag.',
  },

  'edi-short-dividend-cost': {
    title: 'Short Dividend Cost',
    definition:
      'When you short a stock, you owe dividends to the lender. This is the estimated annual dividend yield on short positions that must be paid out.',
    formula: 'Dividend Cost = Collateral × Short Ratio × Short Dividend Rate',
    impact:
      'Typically 1.0-2.0% for broad equity shorts. This is a real cost that reduces net returns. Partially offset by dividends received on long positions.',
  },

  'edi-incremental-financing': {
    title: 'Incremental Financing Cost',
    definition:
      'The total annual cost of running the overlay, computed from margin interest, stock borrow fees, and short dividend costs. This is the key cost that must be recovered through tax savings.',
    formula: '(Margin Rate × Long Leverage) + ((Borrow Rate + Dividend Rate) × Short Ratio)',
    impact:
      'This rate compounds against the portfolio annually, reducing EDI value vs. passive. The Protection Ratio measures how efficiently this cost translates into tax protection.',
  },

  // ============================================
  // EDI TAB — YEAR-BY-YEAR TABLE ROWS
  // ============================================

  'edi-collateral-value-row': {
    title: 'Collateral Value',
    definition:
      'The portfolio value at the start of this year, after growth from prior year. Grows at the annual return minus financing drag (net growth rate).',
    formula: 'Prior Year Value × (1 + Annual Return - Financing Cost Rate)',
    impact:
      'The base on which all ST loss and LT gain rates are applied. Higher values generate more absolute losses and gains.',
  },

  'edi-st-losses-harvested': {
    title: 'ST Losses Harvested',
    definition:
      'Short-term capital losses generated by actively rebalancing the overlay strategy. As individual positions decline, they are sold to realize losses before they become long-term.',
    formula: 'Collateral Value × Strategy ST Loss Rate × (1 - Wash Sale Rate)',
    impact:
      'The primary driver of carryforward accumulation. Rates decline over time as the portfolio matures and "easy" harvesting opportunities diminish.',
  },

  'edi-lt-gains-realized': {
    title: 'LT Gains Realized',
    definition:
      'Long-term capital gains from positions that appreciated and crossed the 1-year holding period threshold. An unavoidable cost of active rebalancing.',
    formula: 'Collateral Value × Strategy LT Gain Rate',
    impact:
      'These gains must be paid for at LT rates, but are first sheltered by ST losses via IRC netting. A low LT gain rate relative to ST loss rate indicates an efficient strategy.',
  },

  'edi-st-offset-lt': {
    title: 'ST Losses Offsetting LT Gains',
    definition:
      'Under IRC netting rules, short-term losses are applied to long-term gains first, before any excess flows to carryforward. This is mandatory — you cannot choose to skip this step.',
    formula: 'min(ST Losses Harvested, LT Gains Realized)',
    impact:
      'This shelters LT gains from tax. The more ST losses exceed LT gains (high harvesting efficiency), the more excess flows to carryforward.',
  },

  'edi-prior-cf-used': {
    title: 'Prior CF Used vs LT Gains',
    definition:
      'Carryforward from prior years applied to remaining LT gains (after current-year ST losses have been applied). LT carryforward offsets LT gains first, then ST carryforward cross-applies.',
    formula: 'min(Prior CF, LT Gains after ST offset)',
    impact:
      'In early years this is usually zero (ST losses exceed LT gains). In later years as harvesting slows, prior CF may be needed to shelter LT gains.',
  },

  'edi-tax-remaining-lt': {
    title: 'Tax on Remaining LT Gains',
    definition:
      'Tax owed on LT gains that could not be sheltered by either current-year ST losses or prior carryforward. This is the strategy\'s annual tax cost.',
    formula: 'Remaining LT Gain × Combined LT Rate',
    impact:
      'Ideally zero or near-zero in early years when ST losses greatly exceed LT gains. May become positive in later years as harvesting efficiency declines.',
  },

  'edi-excess-st-to-cf': {
    title: 'Excess ST Loss to CF',
    definition:
      'After offsetting LT gains, remaining ST losses flow to carryforward. This is the net new addition to your accumulated tax asset each year.',
    formula: 'ST Losses Harvested - ST Losses Used to Offset LT Gains',
    impact:
      'The key driver of CF accumulation. Larger excess means faster CF growth. This amount retains its ST character in carryforward per IRC §1212(b).',
  },

  'edi-capital-loss-deduction': {
    title: '$3K Capital Loss Deduction',
    definition:
      'IRC §1211(b) allows up to $3,000/year ($1,500 for MFS) of net capital losses to offset ordinary income. Consumed from ST carryforward first, then LT.',
    formula: 'min(Available CF, $3,000 or $1,500 for MFS)',
    impact:
      'A small but certain annual benefit. At a ~50% combined rate, this saves ~$1,500/year. The deduction is consumed from CF, slightly reducing future gain-sheltering capacity.',
  },

  'edi-tax-saved-deduction': {
    title: 'Tax Saved (Deduction)',
    definition:
      'Tax savings from the $3K capital loss deduction. Calculated at the combined ST rate MINUS NIIT, because this deduction offsets ordinary income, not net investment income.',
    formula: '$3K Deduction × (Combined ST Rate - 3.8% NIIT)',
    impact:
      'The NIIT exclusion matters: using the full combined rate would overstate savings by $114/year. This is the only "realized" (certain) benefit each year.',
  },

  'edi-net-annual-benefit': {
    title: 'Net Annual Realized Benefit',
    definition:
      'The net cash-in-pocket from the strategy this year: tax saved from the $3K deduction minus tax paid on any remaining LT gains. Positive means net savings.',
    formula: 'Tax Saved by $3K Deduction - Tax on Remaining LT Gains',
    impact:
      'Usually positive in early years (ST losses far exceed LT gains, so LT gain tax is zero). This is the "realized" benefit — it occurs whether or not a gain event happens.',
  },

  'edi-st-carryforward': {
    title: 'ST Carryforward',
    definition:
      'Accumulated short-term capital loss carryforward. Retains ST character per IRC §1212(b), meaning it offsets ST gains first, then cross-applies to LT gains.',
    formula: 'Prior ST CF + Excess ST Loss - ST CF Used vs LT Gains - ST CF Used for $3K Deduction',
    impact:
      'The bulk of accumulated CF is ST character. When applied against future LT gains, the tax savings rate is the LT rate (not the higher ST rate).',
  },

  'edi-lt-carryforward': {
    title: 'LT Carryforward',
    definition:
      'Accumulated long-term capital loss carryforward. Usually small or zero for this strategy since LT losses are rare — the strategy harvests ST losses.',
    impact:
      'LT carryforward offsets LT gains first (same character). In practice, nearly all accumulated CF from this strategy is ST character.',
  },

  'edi-total-carryforward': {
    title: 'Total Carryforward',
    definition:
      'Sum of ST and LT carryforward — the total tax asset accumulated. This amount can shelter future capital gains dollar-for-dollar with no annual limit.',
    formula: 'ST Carryforward + LT Carryforward',
    impact:
      'The core asset built by this strategy. A $5M carryforward can shelter a $5M gain in a single year, saving ~$1.86M in tax at a 37.1% combined LT rate. There is no annual limit on using CF against gains.',
  },

  'edi-harvesting-efficiency': {
    title: 'Harvesting Efficiency (ST/LT)',
    definition:
      'Ratio of ST losses harvested per dollar of LT gains realized. Higher ratios mean the strategy is generating more losses relative to its gain cost.',
    formula: 'ST Losses Harvested ÷ LT Gains Realized',
    impact:
      'Ratios above 3× are excellent. Declining efficiency over time is expected as "easy" losses are exhausted. Year 1 typically shows the highest ratio.',
  },

  // ============================================
  // EDI TAB — PROTECTION VALUE TABLE
  // ============================================

  'edi-cumulative-financing': {
    title: 'Cumulative Financing Cost',
    definition:
      'Running total of incremental financing costs (margin interest + stock borrow + short dividends) paid since inception. This is the cost that must be recovered through tax savings.',
    formula: 'Sum of (Collateral Value × Financing Rate) for each year',
    impact:
      'Grows as portfolio compounds. This is the denominator of the Protection Ratio and the cost that the Break-Even Gain Event must recover.',
  },

  'edi-cf-protection-built': {
    title: 'CF Protection Built',
    definition:
      'New carryforward added this year (net change in total CF). In early years, large CF additions; later years, smaller additions as harvesting efficiency declines.',
    formula: 'Current Year Ending CF - Prior Year Ending CF',
    impact:
      'Multiplied by the combined LT rate, this gives the "protection value" built this year. Year 1 typically builds the most protection.',
  },

  'edi-protection-ratio-row': {
    title: 'Protection Ratio',
    definition:
      'Cumulative CF tax shield value divided by cumulative financing cost. Shows how much potential tax protection has been built per dollar of cost incurred.',
    formula: '(Cumulative CF × Combined LT Rate) ÷ Cumulative Financing Cost',
    impact:
      'Values above 1.0× mean the strategy has built more potential value than it cost. Note this protection is contingent — it requires a gain event to be realized.',
  },

  'edi-break-even-row': {
    title: 'Break-Even Gain Event',
    definition:
      'The capital gain amount needed to recover net unrecovered financing cost (after crediting $3K deduction savings already banked).',
    formula: 'max(0, Cumulative Cost - Cumulative Realized Benefit) ÷ Combined LT Rate',
    impact:
      'Decreases over time as realized benefits accumulate. If a client expects a gain event larger than this, the strategy has positive expected value.',
  },

  // ============================================
  // EDI TAB — REALIZATION SCENARIOS
  // ============================================

  'edi-tax-without-cf': {
    title: 'Tax Without Carryforward',
    definition:
      'What you would pay in capital gains tax on this gain if you had no carryforward. This is the "do nothing" baseline.',
    formula: 'Gain Amount × Applicable Tax Rate (LT or ST)',
    impact:
      'The comparison point. The difference between this and "Tax With CF" is your strategy\'s dollar value for this specific gain event.',
  },

  'edi-cf-used': {
    title: 'Carryforward Used',
    definition:
      'How much of your accumulated carryforward would be applied to shelter this gain. Same-character CF applies first, then cross-character.',
    formula: 'min(Available CF, Gain Amount)',
    impact:
      'If CF exceeds the gain, it shelters 100% of the gain. Any unused CF remains available for future events.',
  },

  'edi-tax-with-cf': {
    title: 'Tax With Carryforward',
    definition:
      'The actual tax owed after applying your carryforward to shelter the gain. Zero if CF exceeds the gain.',
    formula: 'max(0, Gain - CF Used) × Applicable Rate',
    impact:
      'This is what you actually pay. Compare to "Tax Without CF" to see your savings.',
  },

  'edi-tax-saved': {
    title: 'Tax Saved',
    definition:
      'The dollar value of your carryforward for this specific gain event. This is the concrete, realized benefit of the EDI strategy.',
    formula: 'Tax Without CF - Tax With CF',
    impact:
      'This is the number that answers "what is my CF worth?" For a $10M LT gain at 37.1% rate with full CF shelter, savings can exceed $3.7M.',
  },

  // ============================================
  // EDI TAB — REALIZATION SIZE SENSITIVITY
  // ============================================

  'edi-effective-rate': {
    title: 'Effective Tax Rate',
    definition:
      'Your actual tax rate on this gain after CF shelter. Zero means fully sheltered; the statutory rate means no CF was available or insufficient.',
    formula: 'Tax With CF ÷ Gain Amount × 100%',
    impact:
      'Shows how much protection you have at different gain sizes. Smaller gains may be fully sheltered (0%); larger gains exhaust CF and approach the statutory rate.',
  },

  // ============================================
  // EDI TAB — UNWIND ANALYSIS
  // ============================================

  'edi-portfolio-value-unwind': {
    title: 'Portfolio Value',
    definition:
      'Projected portfolio value at the end of the selected unwind year, after compounding at the net growth rate (annual return minus financing drag).',
    formula: 'Initial Collateral × (1 + Annual Return - Financing Rate)^Year',
    impact:
      'The base from which embedded gain and exit tax are calculated. Higher growth increases both value and embedded gain.',
  },

  'edi-embedded-gain': {
    title: 'Embedded Gain',
    definition:
      'The unrealized gain in the portfolio, consisting of market appreciation PLUS basis reduction from tax-loss harvesting. Harvesting lowers your cost basis, increasing the eventual exit tax.',
    formula: '(Portfolio Value × Market Appreciation%) + Cumulative Basis Reduction from Harvesting',
    impact:
      'Higher than a passive portfolio\'s embedded gain because harvesting reduces basis. This is why CF matters — it shelters this enlarged exit gain.',
  },

  'edi-cf-available': {
    title: 'CF Available',
    definition:
      'Total carryforward (ST + LT) accumulated through this year. This is the amount available to shelter the embedded gain on exit.',
    formula: 'Ending ST Carryforward + Ending LT Carryforward',
    impact:
      'When CF ≥ Embedded Gain, you can exit tax-free. The year this happens is the "Tax-Free Exit Year" shown in the summary cards.',
  },

  'edi-net-unwind-tax': {
    title: 'Net Unwind Tax',
    definition:
      'Tax owed on full liquidation after applying carryforward to shelter the embedded gain. Zero if CF exceeds embedded gain.',
    formula: 'max(0, Embedded Gain - CF Available) × Combined LT Rate',
    impact:
      'This is the "worst case" exit cost. In early years, CF may not fully cover the embedded gain. After the tax-free exit year, this is zero.',
  },

  'edi-gross-unwind-tax': {
    title: 'Gross Unwind Tax',
    definition:
      'What the exit tax would be with NO carryforward — the full embedded gain taxed at the LT rate.',
    formula: 'Embedded Gain × Combined LT Rate',
    impact:
      'The reference point. The difference between Gross and Net Unwind Tax is the value of your carryforward at this exit point.',
  },

  'edi-tax-saved-cf': {
    title: 'Tax Saved by CF',
    definition:
      'Dollar amount of exit tax eliminated by applying carryforward. The concrete value of accumulated CF at this exit point.',
    formula: 'Gross Unwind Tax - Net Unwind Tax',
    impact:
      'Shows the increasing value of CF over time. After the tax-free exit year, this equals the full Gross Unwind Tax (100% shelter).',
  },

  // ============================================
  // EDI TAB — ESTATE PLANNING
  // ============================================

  'edi-step-up-value': {
    title: 'Step-Up Value',
    definition:
      'Tax savings from IRC §1014 basis step-up at death. All unrealized gains are eliminated when positions receive a new cost basis equal to fair market value.',
    formula: 'Embedded Gains × Combined LT Rate',
    impact:
      'The argument for holding: at death, all embedded gains disappear. But carryforwards are also lost (§1212(b)), so the optimal strategy may be partial unwind.',
  },

  'edi-cf-lost-death': {
    title: 'CF Lost at Death',
    definition:
      'The tax value of carryforward that would be permanently lost at death. Per IRC §1212(b), capital loss carryforwards are non-transferable and expire upon death.',
    formula: 'Total Carryforward × Combined LT Rate',
    impact:
      'This is the cost of not using your CF before death. If CF is large, a partial unwind to use it (tax-free via CF shelter) may be optimal.',
  },

  'edi-optimal-unwind': {
    title: 'Optimal Unwind %',
    definition:
      'The fraction of the portfolio that can be liquidated tax-free using available CF. The remaining portion benefits from step-up at death.',
    formula: 'min(Total CF ÷ Embedded Gain per share, 100%)',
    impact:
      'The recommended estate strategy: unwind this percentage (sheltered by CF) and hold the rest for step-up. Maximizes total tax benefit.',
  },

  // ============================================
  // EDI TAB — STRATEGY COST & PROTECTION
  // ============================================

  'edi-annual-financing-cost': {
    title: 'Annual Financing Cost (Incremental)',
    definition:
      'This year\'s cost of maintaining the overlay: margin interest on long leverage, stock borrow fees on short positions, and short dividend payments.',
    formula: 'Collateral Value × Incremental Financing Rate',
    impact:
      'Grows as the portfolio compounds. This is the incremental cost of EDI vs. passive — the cost that CF must recover to justify the strategy.',
  },

  'edi-advisory-fee-row': {
    title: 'Advisory Fee (Paid Regardless)',
    definition:
      'The wealth management fee charged on NAV. Shown for context but NOT included in incremental cost — it is paid whether the client chooses passive, traditional DI, or EDI.',
    formula: 'Collateral Value × Advisory Fee Rate',
    impact:
      'Not part of the EDI cost/benefit analysis. Common to all strategies, so excluded from Protection Ratio and Break-Even calculations.',
  },

  'edi-cumulative-cf': {
    title: 'Cumulative CF Protection',
    definition:
      'Running total of carryforward built from inception. Represents the total tax asset accumulated by the strategy.',
    formula: 'Sum of (CF Protection Built) for each year',
    impact:
      'This is the numerator (times LT rate) of the Protection Ratio. The higher this goes relative to cumulative cost, the better the strategy economics.',
  },

  'edi-protection-cost-ratio': {
    title: 'Protection-to-Cost Ratio',
    definition:
      'How much tax protection value (CF × LT rate) has been generated per dollar of incremental financing cost. The key efficiency metric.',
    formula: '(Cumulative CF × Combined LT Rate) ÷ Cumulative Financing Cost',
    impact:
      'Above 1.0× means more protection than cost. Typically 2-4× for well-structured overlay strategies. The protection only materializes with a gain event.',
  },

  // ============================================
  // EDI TAB — LIQUIDATION COMPARISON
  // ============================================

  'edi-passive-after-tax': {
    title: 'Passive After-Tax',
    definition:
      'Terminal portfolio value of a buy-and-hold approach after paying exit tax on all unrealized gains. No tax-loss harvesting, no financing costs.',
    formula: '(Initial × (1 + Return)^Years) - (Market Gain × Combined LT Rate)',
    impact:
      'The simplest baseline. No strategy costs, but also no CF protection. All embedded gains are fully taxed at liquidation.',
  },

  'edi-trad-di-after-tax': {
    title: 'Traditional DI After-Tax',
    definition:
      'Terminal value of a long-only tax-loss harvesting strategy (like Parametric, Aperio, Wealthfront). Same gross return as passive, no financing costs, but builds modest CF through TLH.',
    formula: 'Gross Value - max(0, Embedded Gain - TLH Carryforward) × LT Rate',
    impact:
      'Shows what basic, low-cost TLH achieves. Industry TLH rates are much lower than EDI overlay rates, so CF accumulation is slower.',
  },

  'edi-edi-after-tax': {
    title: 'EDI After-Tax',
    definition:
      'Terminal value of the EDI overlay strategy after exit tax. Gross value is reduced by financing drag, but exit tax is reduced by the much larger CF shelter.',
    formula: 'EDI Value (with drag) - max(0, Embedded Gain - EDI Carryforward) × LT Rate',
    impact:
      'In a forced liquidation, EDI may show lower terminal wealth than passive (financing drag). The real EDI value is in CF for external events, not terminal liquidation.',
  },

  'edi-tlh-benefit': {
    title: 'TLH Benefit (Trad DI vs Passive)',
    definition:
      'The after-tax wealth improvement from basic tax-loss harvesting compared to doing nothing. This is the value of TLH alone, without the overlay.',
    formula: 'Traditional DI After-Tax - Passive After-Tax',
    impact:
      'In a forced liquidation, TLH provides modest benefit since basis reduction partially offsets CF shelter. The real TLH value is in CF for external gain events.',
  },

  'edi-upgrade-value': {
    title: 'EDI Upgrade Value (EDI vs Trad DI)',
    definition:
      'The incremental value of the EDI overlay versus traditional long-only DI at full liquidation. Answers: "why pay for the overlay?"',
    formula: 'EDI After-Tax - Traditional DI After-Tax',
    impact:
      'In forced liquidation, this may be negative (financing drag). But EDI builds 5-10× more CF, so for external events (stock sales, business exits), EDI provides dramatically more protection.',
  },

  'edi-trad-di-cf-built': {
    title: 'Traditional DI CF Built',
    definition:
      'Carryforward accumulated by traditional long-only TLH using industry-benchmark loss rates (5% Year 1, declining to 1.5% steady-state). No overlay, no leverage.',
    formula: 'Cumulative net ST losses from TLH, minus $3K/year deduction and LT gain offsets',
    impact:
      'Compare to EDI CF to see the overlay\'s incremental CF generation. Traditional DI typically builds $300-500K CF at year 10 vs. EDI\'s $5-8M+.',
  },

  'edi-edi-vs-trad-di': {
    title: 'EDI vs Trad DI (Per-Year)',
    definition:
      'Year-by-year after-tax advantage of EDI over traditional DI at liquidation. Shows how the comparison evolves as CF builds and financing drag compounds.',
    formula: 'EDI After-Tax - Traditional DI After-Tax (for each year)',
    impact:
      'May start negative (financing drag) and improve over time as EDI CF grows. This is the forced-liquidation view — for external events, EDI\'s larger CF is the differentiator.',
  },

  // ============================================
  // EDI TAB — NIIT BREAKOUT
  // ============================================

  'edi-niit-combined-st': {
    title: 'Combined ST Rate (incl. NIIT)',
    definition:
      'Your total tax rate on ordinary income and short-term capital gains, including the 3.8% Net Investment Income Tax for high earners (AGI > $250K MFJ).',
    formula: 'Federal Ordinary Rate + NIIT (3.8%) + State Rate',
    impact:
      'This rate applies to short-term gains. The differential between this and the LT rate drives the value of ST→LT conversion strategies.',
  },

  'edi-niit-combined-lt': {
    title: 'Combined LT Rate (incl. NIIT)',
    definition:
      'Your total tax rate on long-term capital gains, including the 3.8% NIIT.',
    formula: 'Federal LT Rate + NIIT (3.8%) + State Rate',
    impact:
      'Applied to LT gains realized by the strategy and to exit gains on liquidation. This is the rate at which carryforward saves money.',
  },

  'edi-niit-deduction-rate': {
    title: '$3K Deduction Effective Rate',
    definition:
      'The tax rate applied to the $3K capital loss deduction. Excludes the 3.8% NIIT because this deduction offsets ordinary income, not net investment income.',
    formula: 'Combined ST Rate - 3.8% NIIT',
    impact:
      'Using the full combined rate (including NIIT) would overstate savings by $114/year. The correct treatment excludes NIIT from this specific deduction.',
  },

  'edi-niit-exclusion-benefit': {
    title: 'Annual NIIT Exclusion Benefit',
    definition:
      'Per-year savings from correctly excluding NIIT from the $3K deduction calculation. This is the amount you would overstate if you incorrectly included NIIT.',
    formula: '$3,000 × 3.8% NIIT Rate = $114/year',
    impact:
      'Small but important for accuracy. Over 10 years, this is $1,140 of avoided overstatement. Shows the calculator\'s precision in NIIT handling.',
  },

  // ============================================
  // EDI TAB — STRATEGY COMPARISON TABLE
  // ============================================

  'edi-strategy-financing': {
    title: 'Financing Rate',
    definition:
      'The incremental financing cost rate for this strategy, based on its specific long leverage ratio and short ratio.',
    formula: '(Margin Rate × Long Leverage) + ((Borrow + Dividend) × Short Ratio)',
    impact:
      'Higher-leverage strategies have higher financing but also generate more ST losses. The Protection Ratio shows which strategies are most efficient.',
  },

  'edi-strategy-tax-savings': {
    title: 'Total Tax Savings',
    definition:
      'The sum of realized benefits ($3K deductions) and contingent CF tax shield over the projection period for this strategy.',
    formula: 'Cumulative Realized Benefit + (Final CF × Combined LT Rate)',
    impact:
      'Combines certain and contingent value. Higher numbers are better, but compare against financing cost to assess true value.',
  },

  'edi-strategy-tax-free-exit': {
    title: 'Tax-Free Exit Year',
    definition:
      'The first year at which this strategy\'s CF exceeds its embedded gain, allowing tax-free liquidation.',
    impact:
      'Strategies with higher harvesting rates reach this milestone sooner. Core strategies (no financing drag) may reach it faster despite lower loss rates.',
  },

  // ============================================
  // EDI TAB — STRATEGY × SCENARIO MATRIX
  // ============================================

  'edi-scenario-net-value': {
    title: 'Net Value',
    definition:
      'Tax saved by carryforward minus cumulative financing cost through the event year. Shows the true economic benefit after paying for the strategy.',
    formula: 'Tax Saved by CF − Cumulative Financing Cost (through event year)',
    impact:
      'Higher is better. Core strategies always have $0 financing cost, so their net value equals tax saved. Overlay strategies may save more tax but must overcome financing drag.',
  },

  'edi-best-strategy': {
    title: 'Best Strategy',
    definition:
      'The strategy producing the highest net value for this specific life-event scenario. Accounts for both tax savings and financing cost.',
    impact:
      'The best strategy varies by scenario — large/late events favor aggressive overlay strategies (more CF), while small/early events may favor core strategies (no financing drag). Use this to match strategy selection to likely exit events.',
  },
};

// Helper function to get popup content by key
export function getPopupContent(key: string): PopupContent | undefined {
  return POPUP_CONTENT[key];
}
