// Popup content definitions for all calculated fields
// Each popup includes: definition, formula (if applicable), and impact explanation

export interface PopupContent {
  title: string;
  definition: string;
  formula?: string;
  impact: string;
}

export const POPUP_CONTENT: Record<string, PopupContent> = {
  // ============================================
  // TAX RATES SECTION
  // ============================================

  'federal-st-rate': {
    title: 'Federal Ordinary/ST Rate',
    definition: 'Your marginal federal tax rate on ordinary income and short-term capital gains (assets held less than 1 year).',
    formula: 'Tax Bracket Rate (10-37%) + NIIT (3.8% if AGI > $250K MFJ or $200K Single)',
    impact: 'Higher ordinary rates increase the value of ST→LT conversion and ordinary loss deductions.',
  },

  'federal-lt-rate': {
    title: 'Federal LT Capital Gains Rate',
    definition: 'Your marginal federal tax rate on long-term capital gains (assets held more than 1 year).',
    formula: '0%/15%/20% based on income + NIIT (3.8% if applicable)',
    impact: 'Lower than ordinary rates - this differential creates the tax arbitrage opportunity.',
  },

  'state-rate': {
    title: 'State Tax Rate',
    definition: 'Your state income tax rate. Most states tax capital gains as ordinary income.',
    formula: 'Varies by state (0% in TX, FL, WA; up to 13.3% in CA)',
    impact: 'Higher state rates increase overall tax burden but also increase savings from the strategy.',
  },

  'combined-st-rate': {
    title: 'Combined Ordinary Rate',
    definition: 'Total tax rate on ordinary income and short-term capital gains.',
    formula: 'Federal Ordinary Rate + State Rate',
    impact: 'This is the rate saved when ordinary losses offset W-2 income.',
  },

  'combined-lt-rate': {
    title: 'Combined LT Rate',
    definition: 'Total tax rate on long-term capital gains.',
    formula: 'Federal LT Rate + State Rate',
    impact: 'This is the effective rate paid on strategy LT gains.',
  },

  'st-lt-benefit': {
    title: 'ST→LT Conversion Benefit',
    definition: 'Tax savings per dollar when converting short-term gains to long-term treatment.',
    formula: 'Combined Ordinary Rate - Combined LT Rate',
    impact: 'This differential drives the core value of matching QFAF ST gains with collateral ST losses.',
  },

  // ============================================
  // STRATEGY SIZING SECTION
  // ============================================

  'collateral-value': {
    title: 'Collateral Value',
    definition: 'The amount invested in the direct indexing (Core) or pledged as collateral (Overlay) strategy.',
    impact: 'Larger collateral generates more ST losses, enabling larger QFAF allocation and greater tax benefits.',
  },

  'auto-sized-qfaf': {
    title: 'Auto-Sized QFAF',
    definition: 'Qualified Family Agricultural Fund allocation, automatically sized to match collateral ST loss capacity.',
    formula: '(Collateral × Strategy ST Loss Rate) ÷ 150%',
    impact: 'QFAF generates 150% ST gains and 150% ordinary losses annually. Proper sizing ensures ST gains are fully offset.',
  },

  'total-exposure': {
    title: 'Total Exposure',
    definition: 'Combined value of collateral and QFAF investments.',
    formula: 'Collateral Value + QFAF Value',
    impact: 'Total capital deployed in the strategy. Tax alpha is measured relative to this amount.',
  },

  'qfaf-ratio': {
    title: 'QFAF Ratio',
    definition: 'QFAF allocation as a percentage of collateral.',
    formula: 'QFAF Value ÷ Collateral Value × 100%',
    impact: 'Lower leverage strategies have lower ratios. Core 145/45 typically has ~8.7% ratio.',
  },

  'section-461-limit': {
    title: 'Section 461(l) Limit',
    definition: 'Annual cap on excess business losses that can offset non-business income (W-2, interest, etc.).',
    formula: '$512,000 (MFJ) or $256,000 (Single/MFS/HOH) for 2026',
    impact: 'Ordinary losses above this limit become NOL carryforward instead of immediate deductions.',
  },

  'year1-st-losses': {
    title: 'Year 1 ST Losses',
    definition: 'Short-term capital losses generated by the collateral strategy in year 1.',
    formula: 'Collateral Value × Strategy ST Loss Rate',
    impact: 'These losses offset QFAF ST gains, converting them to long-term treatment.',
  },

  'year1-st-gains': {
    title: 'Year 1 ST Gains',
    definition: 'Short-term capital gains generated by QFAF in year 1.',
    formula: 'QFAF Value × 150%',
    impact: 'Auto-sizing ensures these match collateral ST losses exactly.',
  },

  'net-st-position': {
    title: 'Net ST Position',
    definition: 'Result of matching QFAF ST gains against collateral ST losses.',
    formula: 'QFAF ST Gains - Collateral ST Losses',
    impact: 'Should be $0 or near-zero with proper auto-sizing.',
  },

  'year1-ordinary-losses': {
    title: 'Year 1 Ordinary Losses',
    definition: 'Ordinary losses generated by QFAF through its swap structure.',
    formula: 'QFAF Value × 150%',
    impact: 'These can offset W-2 income, subject to §461(l) limitation.',
  },

  'usable-ordinary-loss': {
    title: 'Usable Ordinary Loss',
    definition: 'Portion of QFAF ordinary losses that can offset income this year.',
    formula: 'min(QFAF Ordinary Losses, §461(l) Limit)',
    impact: 'Directly reduces taxable income at your marginal ordinary rate.',
  },

  'excess-to-nol': {
    title: 'Excess → NOL Carryforward',
    definition: 'Ordinary losses exceeding the §461(l) limit that become Net Operating Loss.',
    formula: 'QFAF Ordinary Losses - Usable Ordinary Loss',
    impact: 'NOL can offset up to 80% of taxable income in future years, carried forward indefinitely.',
  },

  // ============================================
  // RESULTS SUMMARY SECTION
  // ============================================

  'total-tax-savings': {
    title: 'Total Tax Savings',
    definition: 'Cumulative tax benefit over the 10-year projection period.',
    formula: 'Sum of (Baseline Tax - Actual Tax) for each year',
    impact: 'Represents the total value extracted from the strategy versus passive investing.',
  },

  'final-portfolio-value': {
    title: 'Final Portfolio Value',
    definition: 'Projected total value of collateral + QFAF at the end of year 10.',
    formula: 'Initial Investment × (1.07)^10 (assumes 7% annual growth)',
    impact: 'Shows the growth of your invested capital over the projection period.',
  },

  'effective-tax-alpha': {
    title: 'Annualized Tax Alpha',
    definition: 'Average annual tax savings as a percentage of total exposure.',
    formula: 'Total Tax Savings ÷ Total Exposure ÷ 10 years',
    impact: 'Measures strategy efficiency - higher alpha means more tax benefit per dollar invested.',
  },

  'total-nol-generated': {
    title: 'Total NOL Generated',
    definition: 'Cumulative Net Operating Loss created over the projection period.',
    formula: 'Sum of Excess Ordinary Losses across all years',
    impact: 'This NOL can offset future income at 80% of taxable income per year.',
  },

  // ============================================
  // RESULTS TABLE COLUMNS
  // ============================================

  'col-year': {
    title: 'Year',
    definition: 'Projection year (1-10).',
    impact: 'Tax events are calculated based on portfolio values at the start of each year.',
  },

  'col-total-value': {
    title: 'Total Portfolio Value',
    definition: 'Combined value of QFAF and collateral investments.',
    formula: 'QFAF Value + Collateral Value (after 7% annual growth)',
    impact: 'Growing portfolio base increases absolute tax benefits in later years.',
  },

  'col-qfaf-value': {
    title: 'QFAF Value',
    definition: 'Market value of QFAF investment.',
    formula: 'Prior Year QFAF × 1.07 (7% growth)',
    impact: 'Higher QFAF value generates larger ST gains and ordinary losses.',
  },

  'col-collateral-value': {
    title: 'Collateral Value',
    definition: 'Market value of direct indexing or pledged stock.',
    formula: 'Prior Year Collateral × 1.07 (7% growth)',
    impact: 'Higher collateral generates more ST losses for offset capacity.',
  },

  'col-st-gains': {
    title: 'ST Gains (QFAF)',
    definition: 'Short-term capital gains generated by QFAF.',
    formula: 'QFAF Value × 150%',
    impact: 'Offset by collateral ST losses to achieve favorable LT treatment.',
  },

  'col-st-losses': {
    title: 'ST Losses (Collateral)',
    definition: 'Short-term capital losses from tax-loss harvesting and short closures.',
    formula: 'Collateral Value × Strategy ST Loss Rate',
    impact: 'Used to offset QFAF ST gains, converting them to LT treatment.',
  },

  'col-ordinary-loss': {
    title: 'Ordinary Loss',
    definition: 'Ordinary losses generated by QFAF swap structure.',
    formula: 'QFAF Value × 150%',
    impact: 'Can offset W-2/ordinary income, subject to §461(l) cap.',
  },

  'col-usable-loss': {
    title: 'Usable Ordinary Loss',
    definition: 'Ordinary loss amount that can be used this year.',
    formula: 'min(Ordinary Loss, §461(l) Limit)',
    impact: 'Reduces taxable income at marginal ordinary rate.',
  },

  'col-excess-nol': {
    title: 'Excess → NOL',
    definition: 'Ordinary losses above §461(l) limit becoming NOL.',
    formula: 'Ordinary Loss - Usable Ordinary Loss',
    impact: 'Carried forward to offset future taxable income.',
  },

  'col-lt-gains': {
    title: 'LT Gains (Collateral)',
    definition: 'Long-term capital gains from collateral strategy rebalancing.',
    formula: 'Collateral Value × Strategy LT Gain Rate',
    impact: 'Taxed at favorable LT rates, a cost of the strategy.',
  },

  'col-tax-savings': {
    title: 'Tax Savings',
    definition: 'Net tax benefit for this year.',
    formula: 'Baseline Tax - Actual Tax',
    impact: 'Annual value extracted from the tax optimization strategy.',
  },

  'col-cumulative-savings': {
    title: 'Cumulative Tax Savings',
    definition: 'Running total of tax savings through this year.',
    formula: 'Sum of Tax Savings from Year 1 to current year',
    impact: 'Shows total value accumulated from the strategy.',
  },

  'col-nol-carryforward': {
    title: 'NOL Carryforward',
    definition: 'Total unused NOL available for future years.',
    formula: 'Prior NOL + This Year Excess - NOL Used This Year',
    impact: 'Can offset 80% of future taxable income each year.',
  },

  // ============================================
  // ADVANCED MODE - YEAR BY YEAR
  // ============================================

  'w2-income-override': {
    title: 'W-2 Income Override',
    definition: 'Override the annual income for this specific year.',
    impact: 'Affects §461(l) limit calculation and NOL usage (80% of taxable income).',
  },

  'cash-infusion': {
    title: 'Cash Infusion',
    definition: 'Additional capital added to the strategy in this year.',
    formula: 'Added to collateral at year start, triggers QFAF re-sizing',
    impact: 'Increases collateral base, which increases ST loss capacity and required QFAF.',
  },

  // ============================================
  // ADVANCED MODE - SENSITIVITY
  // ============================================

  'sens-federal-rate': {
    title: 'Federal Rate Change',
    definition: 'Model potential changes to federal tax rates.',
    formula: 'Adjusts both ordinary and LT federal rates by this amount',
    impact: 'Higher rates increase strategy value; lower rates decrease it.',
  },

  'sens-state-rate': {
    title: 'State Rate Change',
    definition: 'Model potential changes to state tax rates.',
    impact: 'Similar to federal - higher state rates increase strategy value.',
  },

  'sens-annual-return': {
    title: 'Annual Return',
    definition: 'Model different portfolio growth scenarios.',
    formula: 'Replaces default 7% growth rate for projections',
    impact: 'Negative returns show how strategy performs in bear markets.',
  },

  'sens-tracking-error': {
    title: 'Tracking Error Impact',
    definition: 'Model deviation from expected strategy performance.',
    formula: 'Multiplier on ST loss and LT gain rate variance',
    impact: 'Higher tracking error means more uncertainty in realized tax events.',
  },

  'sens-st-loss-variance': {
    title: 'ST Loss Rate Variance',
    definition: 'Model variation in tax-loss harvesting effectiveness.',
    formula: 'Adjusts strategy ST loss rate by this percentage',
    impact: 'Lower ST losses reduce offset capacity and strategy benefits.',
  },

  'sens-lt-gain-variance': {
    title: 'LT Gain Rate Variance',
    definition: 'Model variation in realized LT gains.',
    formula: 'Adjusts strategy LT gain rate by this percentage',
    impact: 'Higher LT gains increase tax cost; lower gains reduce cost.',
  },

  // ============================================
  // ADVANCED MODE - STRATEGY COMPARISON
  // ============================================

  'comp-qfaf-required': {
    title: 'QFAF Required',
    definition: 'QFAF allocation needed for this strategy.',
    formula: '(Collateral × ST Loss Rate) ÷ 150%',
    impact: 'Higher leverage strategies require proportionally more QFAF.',
  },

  'comp-tracking-error': {
    title: 'Tracking Error',
    definition: 'Expected deviation from benchmark returns.',
    impact: 'Higher tracking error means more return volatility vs. index.',
  },
};

// Helper function to get popup content by key
export function getPopupContent(key: string): PopupContent | undefined {
  return POPUP_CONTENT[key];
}
