// Popup content definitions for all calculated fields
// Each popup includes: definition, formula (if applicable), and impact explanation

export interface PopupContent {
  title: string;
  definition: string;
  formula?: string;
  impact: string;
}

export const POPUP_CONTENT: Record<string, PopupContent> = {
  // ============================================
  // TAX RATES SECTION
  // ============================================

  'federal-st-rate': {
    title: 'Federal Ordinary/ST Rate',
    definition:
      'Your marginal federal tax rate on ordinary income and short-term capital gains (assets held less than 1 year).',
    formula: 'Tax Bracket Rate (10-37%) + NIIT (3.8% if AGI > $250K MFJ or $200K Single)',
    impact:
      'Higher ordinary rates increase the value of ST→LT conversion and ordinary loss deductions.',
  },

  'federal-lt-rate': {
    title: 'Federal LT Capital Gains Rate',
    definition:
      'Your marginal federal tax rate on long-term capital gains (assets held more than 1 year).',
    formula: '0%/15%/20% based on income + NIIT (3.8% if applicable)',
    impact: 'Lower than ordinary rates - this differential creates the tax arbitrage opportunity.',
  },

  'state-rate': {
    title: 'State Tax Rate',
    definition: 'Your state income tax rate. Most states tax capital gains as ordinary income.',
    formula: 'Varies by state (0% in TX, FL, WA; up to 13.3% in CA)',
    impact:
      'Higher state rates increase overall tax burden but also increase savings from the strategy.',
  },

  'combined-st-rate': {
    title: 'Combined Ordinary Rate',
    definition: 'Total tax rate on ordinary income and short-term capital gains.',
    formula: 'Federal Ordinary Rate + State Rate',
    impact: 'This is the rate saved when ordinary losses offset W-2 income.',
  },

  'combined-lt-rate': {
    title: 'Combined LT Rate',
    definition: 'Total tax rate on long-term capital gains.',
    formula: 'Federal LT Rate + State Rate',
    impact: 'This is the effective rate paid on strategy LT gains.',
  },

  'st-lt-benefit': {
    title: 'ST→LT Conversion Benefit',
    definition: 'Tax savings per dollar when converting short-term gains to long-term treatment.',
    formula: 'Combined Ordinary Rate - Combined LT Rate',
    impact:
      'This differential drives the core value of matching QFAF ST gains with collateral ST losses.',
  },

  // ============================================
  // STRATEGY SIZING SECTION
  // ============================================

  'collateral-value': {
    title: 'Collateral Value',
    definition:
      'The amount invested in the direct indexing (Core) or pledged as collateral (Overlay) strategy.',
    impact:
      'Larger collateral generates more ST losses, enabling larger QFAF allocation and greater tax benefits.',
  },

  'auto-sized-qfaf': {
    title: 'Auto-Sized QFAF',
    definition:
      'Qualified Family Agricultural Fund allocation, automatically sized to match collateral ST loss capacity.',
    formula: '(Collateral × Strategy ST Loss Rate) ÷ 150%',
    impact:
      'QFAF generates 150% ST gains and 150% ordinary losses annually. Proper sizing ensures ST gains are fully offset.',
  },

  'total-exposure': {
    title: 'Total Exposure',
    definition: 'Combined value of collateral and QFAF investments.',
    formula: 'Collateral Value + QFAF Value',
    impact:
      'Total capital deployed in the strategy. Tax alpha is measured relative to this amount.',
  },

  'qfaf-ratio': {
    title: 'QFAF Ratio',
    definition: 'QFAF allocation as a percentage of collateral.',
    formula: 'QFAF Value ÷ Collateral Value × 100%',
    impact: 'Lower leverage strategies have lower ratios. Core 145/45 typically has ~8.7% ratio.',
  },

  'section-461-limit': {
    title: 'Section 461(l) Limit',
    definition:
      'Annual cap on excess business losses that can offset non-business income (W-2, interest, etc.).',
    formula:
      '$512,000 (MFJ) or $256,000 (Single/MFS/HOH) for 2026. Also limited by taxable income.',
    impact: 'Ordinary losses above this limit (or taxable income) become NOL carryforward.',
  },

  'year1-st-losses': {
    title: 'Year 1 ST Losses',
    definition: 'Short-term capital losses generated by the collateral strategy in year 1.',
    formula: 'Collateral Value × Strategy ST Loss Rate',
    impact: 'These losses offset QFAF ST gains, converting them to long-term treatment.',
  },

  'year1-st-gains': {
    title: 'Year 1 ST Gains',
    definition: 'Short-term capital gains generated by QFAF in year 1.',
    formula: 'QFAF Value × 150%',
    impact: 'Auto-sizing ensures these match collateral ST losses exactly.',
  },

  'net-st-position': {
    title: 'Net ST Position',
    definition: 'Result of matching QFAF ST gains against collateral ST losses.',
    formula: 'QFAF ST Gains - Collateral ST Losses',
    impact: 'Should be $0 or near-zero with proper auto-sizing.',
  },

  'year1-ordinary-losses': {
    title: 'Year 1 Ordinary Losses',
    definition: 'Ordinary losses generated by QFAF through its swap structure.',
    formula: 'QFAF Value × 150%',
    impact: 'These can offset W-2 income, subject to §461(l) limitation.',
  },

  'usable-ordinary-loss': {
    title: 'Usable Ordinary Loss',
    definition: 'Portion of QFAF ordinary losses that can offset income this year.',
    formula: 'min(QFAF Ordinary Losses, §461(l) Limit)',
    impact: 'Directly reduces taxable income at your marginal ordinary rate.',
  },

  'excess-to-nol': {
    title: 'Excess → NOL Carryforward',
    definition: 'Ordinary losses exceeding the §461(l) limit that become Net Operating Loss.',
    formula: 'QFAF Ordinary Losses - Usable Ordinary Loss',
    impact:
      'NOL can offset up to 80% of taxable income in future years, carried forward indefinitely.',
  },

  // ============================================
  // TAX BENEFIT BREAKDOWN
  // ============================================

  'ordinary-loss-benefit': {
    title: 'Ordinary Loss Tax Benefit',
    definition: 'Tax savings from QFAF ordinary losses offsetting W-2/ordinary income.',
    formula: 'Usable Ordinary Loss × Combined Ordinary Rate',
    impact: 'The primary driver of tax alpha. Higher ordinary rates = greater benefit.',
  },

  'st-lt-conversion-benefit': {
    title: 'ST→LT Conversion Benefit',
    definition:
      'Tax savings from converting short-term gains (taxed at ordinary rates) to long-term treatment.',
    formula: 'Matched ST Amount × (Ordinary Rate - LT Rate)',
    impact:
      'By matching QFAF ST gains with collateral ST losses, gains are effectively taxed at LT rates.',
  },

  'lt-gain-cost': {
    title: 'LT Gain Tax Cost',
    definition:
      'Tax paid on long-term capital gains realized from collateral strategy rebalancing.',
    formula: 'LT Gains Realized × Combined LT Rate',
    impact: 'A necessary cost of the strategy, but taxed at favorable long-term rates.',
  },

  'year1-tax-savings': {
    title: 'Net Year 1 Tax Savings',
    definition: 'Total tax benefit in Year 1 after accounting for all tax events.',
    formula: 'Ordinary Loss Benefit + ST→LT Benefit - LT Gain Cost',
    impact: 'Represents immediate tax alpha generated by the strategy.',
  },

  'nol-offset-benefit': {
    title: 'NOL Offset Benefit',
    definition:
      'Tax savings from using accumulated Net Operating Loss (NOL) carryforward to offset current year taxable income.',
    formula: 'NOL Used This Year × Combined Ordinary Rate',
    impact:
      "Starting in Year 2, accumulated NOL from prior years can offset up to 80% of taxable income, providing additional tax savings beyond the current year's ordinary loss deduction.",
  },

  'year2-tax-savings': {
    title: 'Net Year 2 Tax Savings',
    definition:
      'Total tax benefit in Year 2 after accounting for all tax events including NOL usage.',
    formula: 'Ordinary Loss Benefit + ST→LT Benefit + NOL Offset Benefit - LT Gain Cost',
    impact:
      'Year 2+ benefits include NOL carryforward usage, which can significantly increase tax savings compared to Year 1.',
  },

  // ============================================
  // RESULTS SUMMARY SECTION
  // ============================================

  'total-tax-savings': {
    title: 'Total Tax Savings',
    definition: 'Cumulative tax benefit over the 10-year projection period.',
    formula: 'Sum of (Baseline Tax - Actual Tax) for each year',
    impact: 'Represents the total value extracted from the strategy versus passive investing.',
  },

  'final-portfolio-value': {
    title: 'Final Portfolio Value',
    definition: 'Projected total value of collateral + QFAF at the end of year 10.',
    formula: 'Initial Investment × (1.07)^10 (assumes 7% annual growth)',
    impact: 'Shows the growth of your invested capital over the projection period.',
  },

  'effective-tax-alpha': {
    title: 'Annualized Tax Alpha',
    definition: 'Average annual tax savings as a percentage of total exposure.',
    formula: 'Total Tax Savings ÷ Total Exposure ÷ 10 years',
    impact:
      'Measures strategy efficiency - higher alpha means more tax benefit per dollar invested.',
  },

  'total-nol-generated': {
    title: 'Total NOL Generated',
    definition: 'Cumulative Net Operating Loss created over the projection period.',
    formula: 'Sum of Excess Ordinary Losses across all years',
    impact: 'This NOL can offset future income at 80% of taxable income per year.',
  },

  // ============================================
  // RESULTS TABLE COLUMNS
  // ============================================

  'col-year': {
    title: 'Year',
    definition: 'Projection year (1-10).',
    impact: 'Tax events are calculated based on portfolio values at the start of each year.',
  },

  'col-total-value': {
    title: 'Total Portfolio Value',
    definition: 'Combined value of QFAF and collateral investments.',
    formula: 'QFAF Value + Collateral Value (after 7% annual growth)',
    impact: 'Growing portfolio base increases absolute tax benefits in later years.',
  },

  'col-portfolio-value': {
    title: 'Total Portfolio Value',
    definition:
      'Combined value of collateral and QFAF positions. Click to expand and see individual components.',
    formula: 'Collateral Value + QFAF Value',
    impact:
      'The total market value of all strategy assets. Growth comes from market returns on both positions.',
  },

  'col-qfaf-value': {
    title: 'QFAF Value',
    definition: 'Market value of QFAF investment.',
    formula: 'Prior Year QFAF × 1.07 (7% growth)',
    impact: 'Higher QFAF value generates larger ST gains and ordinary losses.',
  },

  'col-collateral-value': {
    title: 'Collateral Value',
    definition: 'Market value of direct indexing or pledged stock.',
    formula: 'Prior Year Collateral × 1.07 (7% growth)',
    impact: 'Higher collateral generates more ST losses for offset capacity.',
  },

  'col-st-gains': {
    title: 'ST Gains (QFAF)',
    definition: 'Short-term capital gains generated by QFAF.',
    formula: 'QFAF Value × 150%',
    impact: 'Offset by collateral ST losses to achieve favorable LT treatment.',
  },

  'col-st-losses': {
    title: 'ST Losses (Collateral)',
    definition: 'Short-term capital losses from tax-loss harvesting and short closures.',
    formula: 'Collateral Value × Strategy ST Loss Rate',
    impact: 'Used to offset QFAF ST gains, converting them to LT treatment.',
  },

  'col-ordinary-loss': {
    title: 'Ordinary Loss',
    definition: 'Ordinary losses generated by QFAF swap structure.',
    formula: 'QFAF Value × 150%',
    impact: 'Can offset W-2/ordinary income, subject to §461(l) cap.',
  },

  'col-usable-loss': {
    title: 'Usable Ordinary Loss',
    definition: 'Ordinary loss amount that can be used this year.',
    formula: 'min(Ordinary Loss, §461(l) Limit)',
    impact: 'Reduces taxable income at marginal ordinary rate.',
  },

  'col-excess-nol': {
    title: 'Excess → NOL',
    definition: 'Ordinary losses above §461(l) limit becoming NOL.',
    formula: 'Ordinary Loss - Usable Ordinary Loss',
    impact: 'Carried forward to offset future taxable income.',
  },

  'col-lt-gains': {
    title: 'LT Gains (Collateral)',
    definition: 'Long-term capital gains from collateral strategy rebalancing.',
    formula: 'Collateral Value × Strategy LT Gain Rate',
    impact: 'Taxed at favorable LT rates, a cost of the strategy.',
  },

  'col-cap-loss-income': {
    title: 'Capital Loss vs Income',
    definition:
      'Unused capital loss carryforward applied against ordinary income per IRC §1211(b).',
    formula: 'min(Remaining Capital Loss Carryforward, $3,000)',
    impact: 'Reduces ordinary income by up to $3,000/year, saving taxes at your marginal rate.',
  },

  'col-nol-used': {
    title: 'NOL Used',
    definition: 'Net Operating Loss carryforward applied this year.',
    formula: 'min(NOL Carryforward, 80% × Taxable Income)',
    impact: 'Reduces taxable income, but limited to 80% of pre-NOL taxable income per TCJA rules.',
  },

  'col-tax-savings': {
    title: 'Tax Savings',
    definition: 'Net tax benefit for this year.',
    formula: 'Baseline Tax - Actual Tax',
    impact: 'Annual value extracted from the tax optimization strategy.',
  },

  'col-cumulative-savings': {
    title: 'Cumulative Tax Savings',
    definition: 'Running total of tax savings through this year.',
    formula: 'Sum of Tax Savings from Year 1 to current year',
    impact: 'Shows total value accumulated from the strategy.',
  },

  'col-eff-rate': {
    title: 'Effective ST Loss Rate',
    definition:
      'The actual ST loss rate used for this year (includes decay and any custom overrides).',
    formula: 'Custom Rate OR (Base Rate × 0.93^(year-1))',
    impact: 'Edit rates using the "Edit Rates by Year" button. Changes affect ST losses harvested.',
  },

  'col-st-carryforward': {
    title: 'ST Capital Loss Carryforward',
    definition: 'Accumulated short-term capital losses not yet used.',
    formula: 'Prior C/F + Current Year Net ST Loss - Used vs LT Gains - $3K Ordinary',
    impact: 'Offsets future capital gains; $3K/year against ordinary income.',
  },

  'col-nol-carryforward': {
    title: 'NOL Carryforward',
    definition: 'Total unused NOL available for future years.',
    formula: 'Prior NOL + This Year Excess - NOL Used This Year',
    impact: 'Can offset 80% of future taxable income each year.',
  },

  'col-net-capital': {
    title: 'Net Capital Activity',
    definition:
      'The net result of all capital gains and losses for the year. Click to expand and see component details (ST Losses, LT Gains, ST Gains).',
    formula: 'QFAF ST Gains - Collateral ST Losses + Collateral LT Gains',
    impact:
      'With proper auto-sizing, net capital ≈ LT gains only (ST gains and losses offset). This is what flows to your tax return.',
  },

  'col-nol-activity': {
    title: 'NOL Activity',
    definition:
      'Net change in NOL for the year. Shows whether NOL is building (+) or being used (−). Click to expand for details.',
    formula: 'NOL Generated (Excess Ordinary Loss) - NOL Used This Year',
    impact:
      'Positive values mean NOL is accumulating faster than it can be used. NOL usage is limited to 80% of taxable income per year.',
  },

  // ============================================
  // ADVANCED MODE - YEAR BY YEAR
  // ============================================

  'w2-income-override': {
    title: 'W-2 Income Override',
    definition: 'Override the annual income for this specific year.',
    impact: 'Affects §461(l) limit calculation and NOL usage (80% of taxable income).',
  },

  'cash-infusion': {
    title: 'Cash Infusion',
    definition: 'Additional capital added to the strategy in this year.',
    formula: 'Added to collateral at year start, triggers QFAF re-sizing',
    impact: 'Increases collateral base, which increases ST loss capacity and required QFAF.',
  },

  // ============================================
  // ADVANCED MODE - SENSITIVITY
  // ============================================

  'sens-federal-rate': {
    title: 'Federal Rate Change',
    definition: 'Model potential changes to federal tax rates.',
    formula: 'Adjusts both ordinary and LT federal rates by this amount',
    impact: 'Higher rates increase strategy value; lower rates decrease it.',
  },

  'sens-state-rate': {
    title: 'State Rate Change',
    definition: 'Model potential changes to state tax rates.',
    impact: 'Similar to federal - higher state rates increase strategy value.',
  },

  'sens-annual-return': {
    title: 'Annual Return',
    definition: 'Model different portfolio growth scenarios.',
    formula: 'Replaces default 7% growth rate for projections',
    impact: 'Negative returns show how strategy performs in bear markets.',
  },

  'sens-tracking-error': {
    title: 'Tracking Error Impact',
    definition: 'Model deviation from expected strategy performance.',
    formula: 'Multiplier on ST loss and LT gain rate variance',
    impact: 'Higher tracking error means more uncertainty in realized tax events.',
  },

  'sens-st-loss-variance': {
    title: 'ST Loss Rate Variance',
    definition: 'Model variation in tax-loss harvesting effectiveness.',
    formula: 'Adjusts strategy ST loss rate by this percentage',
    impact: 'Lower ST losses reduce offset capacity and strategy benefits.',
  },

  'sens-lt-gain-variance': {
    title: 'LT Gain Rate Variance',
    definition: 'Model variation in realized LT gains.',
    formula: 'Adjusts strategy LT gain rate by this percentage',
    impact: 'Higher LT gains increase tax cost; lower gains reduce cost.',
  },

  // ============================================
  // ADVANCED MODE - STRATEGY COMPARISON
  // ============================================

  'comp-qfaf-required': {
    title: 'QFAF Required',
    definition: 'QFAF allocation needed for this strategy.',
    formula: '(Collateral × ST Loss Rate) ÷ 150%',
    impact: 'Higher leverage strategies require proportionally more QFAF.',
  },

  'comp-tracking-error': {
    title: 'Tracking Error',
    definition: 'Expected deviation from benchmark returns.',
    impact: 'Higher tracking error means more return volatility vs. index.',
  },

  // ============================================
  // ADVANCED MODE - SETTINGS
  // ============================================

  'setting-qfaf-multiplier': {
    title: 'QFAF Multiplier',
    definition:
      'The rate at which QFAF generates both ST gains and ordinary losses relative to its market value.',
    formula: 'Default: 150% (1.50x)',
    impact: 'Changing this affects auto-sizing and all tax event calculations.',
  },

  'setting-qfaf-growth': {
    title: 'QFAF Growth',
    definition: 'Controls whether the QFAF position appreciates with market returns over time.',
    formula: 'Enabled: QFAF grows at (Annual Return - Financing Cost). Disabled: QFAF stays flat.',
    impact:
      'Disabling models scenarios where QFAF returns are eaten by fees, hedging costs, or manager underperformance. This reduces final portfolio value but does not affect annual tax benefits.',
  },

  'setting-wash-sale': {
    title: 'Wash Sale Disallowance',
    definition:
      'Percentage of ST losses disallowed due to wash sale rule violations when repurchasing substantially identical securities within 30 days.',
    formula: 'Effective ST Losses = Gross ST Losses × (1 - Wash Sale Rate)',
    impact:
      'Typically 5-15% of losses are disallowed. Higher rates reduce ST offset capacity and overall tax benefits.',
  },

  'setting-nol-offset': {
    title: 'NOL Offset Limit',
    definition:
      'Maximum percentage of taxable income that can be offset by NOL carryforward in any given year.',
    formula: 'Default: 80% (per TCJA post-2017 rules)',
    impact: 'Lower limits extend NOL usage over more years; higher limits accelerate utilization.',
  },

  'setting-annual-return': {
    title: 'Default Annual Return',
    definition: 'Assumed portfolio growth rate for multi-year projections.',
    formula: 'Default: 7% (historical equity average)',
    impact: 'Higher returns compound portfolio value; lower returns reduce projected wealth.',
  },

  'setting-niit': {
    title: 'NIIT Rate',
    definition:
      'Net Investment Income Tax on investment income above thresholds ($250K MFJ, $200K Single).',
    formula: 'Default: 3.8%',
    impact: 'Added to capital gains rates for high earners.',
  },

  'setting-ltcg': {
    title: 'LTCG Rate',
    definition: 'Federal long-term capital gains rate (top bracket).',
    formula: 'Default: 20%',
    impact: 'Lower LT rates increase the value of ST→LT conversion.',
  },

  'setting-stcg': {
    title: 'Top Ordinary Rate',
    definition: 'Highest marginal federal ordinary income tax rate.',
    formula: 'Default: 37%',
    impact: 'Higher ordinary rates increase the value of ordinary loss deductions.',
  },
};

// Helper function to get popup content by key
export function getPopupContent(key: string): PopupContent | undefined {
  return POPUP_CONTENT[key];
}
